apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-$GIT_BRANCH
  labels:
    commit: $GIT_COMMIT
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest_api
        branch: $GIT_BRANCH
        commit: $GIT_COMMIT
        environment: staging
    spec:
      volumes:
      - name: auth-volume
        secret:
          secretName: rest-auth
      containers:
      - name: rest-api
        image: "$CONTAINER_REPO:$GIT_COMMIT"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            # Path to probe; should be cheap, but representative of typical behavior
            path: /api/latest/public/utils/ping
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/www/app/app/authconf
          name: auth-volume
        env:
        - name: OPENTARGETS_API_CONFIG
          value: "production"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        #set very high usage limits
        - name: USAGE_LIMIT_DEFAULT_SHORT
          value: "1000000"
        - name: USAGE_LIMIT_DEFAULT_LONG
          value: "100000000"
